# Generated by Django 5.2.7 on 2025-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
