# Generated by Django 5.2.7 on 2025-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='webhook_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
